### ISSUE TITLE
Improve the UX in CLI tools using Notifications and oclif-ux

### ISSUE THREAD

**Issue by trooper2013** [forcedotcom/lwc-dev-mobile#19]
e.g. For time consuming operations like creating and booting virtual devices  the use of a spinner will be ideal. 
https://oclif.io/docs/spinner
We could tweak requirements list to behave like listr or employ the use of listr for better user experience.

Notifications can be provided to the user using node-notifier. 
https://oclif.io/docs/notifications

**Comment by maliroteh-sf** [comment]
This was mostly done in `lwc-dev-mobile-core` repo in [this PR.](https://github.com/forcedotcom/lwc-dev-mobile-core/pull/3)
